### ISSUE TITLE
Forbedre eksport av filer

### ISSUE THREAD

**Issue by oscarborke** [staspika/python-klmast#48]
1) Bruker bør kunne velge navn og plassering av .DAT-filen som eksporteres til Fundamast
2) Bruker bør kunne velge navn og plassering av .txt-filen som eksporteres fra Tabell-vinduet
3) Det bør være mulig å navigere mellom lagrede beregninger i form av tabellutskrifter i Tabell-vinduet, tilsvarende KL_fund. Her må også funksjoner for mastenummerering/km implementeres. Se forøvrig KL_funds hjelpefil seksjon F.4 "F.4	Tabell med resultater av beregningene"

**Comment by staspika** [comment]
Duplicate of #57, #58 and #59.

**Comment by staspika** [comment]
Duplicate of #58

**Comment by staspika** [comment]
Duplicate of #59

**Comment by staspika** [comment]
Duplicate of #57 #58 #59

**Comment by staspika** [comment]
Closing this issue after splitting it into #57, #58 and #59 for easier issue management.
